/**
 * Kuwait area names (Arabic) -> areaCode. Used by intent_parser for extractAreaFromText.
 * Matches lib/data/ar_to_en_mapping.dart + _code(en). Sorted by length in use.
 */
export const KUWAIT_AREAS: Record<string, string> = {
  "ضاحية حصه المبارك": "hessa_al_mubarak_district",
  "شمال غرب الصليبخات": "north_west_sulaibikhat",
  "الشويخ السكنية": "shuwaikh_residential",
  "الشويخ الصناعية": "shuwaikh_industrial",
  "القبلة - جبلة": "al_qibla_jibla",
  "عبدالله السالم": "abdullah_al_salem",
  "جابر الاحمد": "jaber_al_ahmad",
  "بنيد القار": "bneid_al_qar",
  "الصالحية": "al_sawlihya",
  "المباركية": "mubarakiya",
  "الدسمة": "dasma",
  "الدعية": "daeya",
  "الفيحاء": "faiha",
  "النزهة": "nuzha",
  "الروضة": "rawda",
  "العديلية": "adailiya",
  "الخالدية": "khaldiya",
  "كيفان": "kaifan",
  "الشامية": "shamiya",
  "اليرموك": "yarmouk",
  "المنصورية": "mansouriya",
  "القادسية": "qadisiya",
  "القيروان": "qairawan",
  "قرطبة": "qurtuba",
  "السرة": "surra",
  "الدوحة": "doha",
  "دسمان": "dasman",
  "غرناطة": "granada",
  "الصليبيخات": "sulaibikhat",
  "النهضة": "nahdha",
  "المرقاب": "al_murqab",
  "الشرق": "sharq",
  "غرب مشرف - مبارك العبدالله": "west_mishref_mubarak_al_abdullah",
  "جنوب السرة": "south_surra",
  "ميدان حولي": "maidan_hawalli",
  "الشعب السكني": "shaab_residential",
  "الشعب البحري": "shaab_marine",
  "حولي": "hawalli",
  "السالمية": "salmiya",
  "البدع": "bidaa",
  "الجابرية": "jabriya",
  "الرميثية": "rumaithiya",
  "مشرف": "mishref",
  "بيان": "bayan",
  "سلوى": "salwa",
  "الزهراء": "zahra",
  "السلام": "al_salam",
  "حطين": "hateen",
  "الشهداء": "shuhada",
  "الصديق": "al_siddiq",
  "العارضية الحرفية - الصناعية": "ardiya_industrial",
  "خيطان الجنوبي الجديدة": "south_new_khaitan",
  "عبدالله المبارك - غرب الجليب": "abdullah_al_mubarak",
  "جليب الشيوخ - الحساوي": "jleeb_al_shuyoukh_hassawi",
  "جنوب عبدالله المبارك": "south_abdullah_al_mubarak",
  "غرب عبدالله المبارك": "west_abdullah_al_mubarak",
  "اسطبلات الفروانية": "farwaniya_stables",
  "الفروانية": "farwaniya",
  "خيطان": "khaitan",
  "الرقعي": "riggae",
  "الضجيج": "dajeej",
  "الري": "rai",
  "الأندلس": "andalous",
  "العارضية": "ardiya",
  "العمرية": "omariya",
  "الرابية": "rabya",
  "الرحاب": "rehab",
  "صباح الناصر": "sabah_al_nasser",
  "اشبيلية": "ishbiliya",
  "الفردوس": "firdous",
  "صباح الاحمد البحرية - الخيران": "sabah_al_ahmad_marine_khiran",
  "علي صباح السالم - ام الهيمان": "ali_sabah_al_salem_umm_al_hayman",
  "صباح الأحمد السكنية": "sabah_al_ahmad_residential",
  "الخيران السكنية - الجانب البري": "khiran_residential_inland",
  "جنوب صباح الأحمد": "south_sabah_al_ahmad",
  "اسطبلات الاحمدي": "ahmadi_stables",
  "الوفرة السكنية": "wafra_housing",
  "مزارع الوفرة": "wafra_farms",
  "فهد الاحمد": "fahad_al_ahmad",
  "الشعيبة الصناعية": "shuaiba_industrial",
  "ميناء عبدالله": "mina_abdullah",
  "جابر العلي": "jaber_al_ali",
  "الاحمدي": "ahmadi",
  "المنقف": "mangaf",
  "الفحيحيل": "fahaheel",
  "أبو حليفة": "abu_halifa",
  "الظهر": "daher",
  "الرقة": "reqqa",
  "هدية": "hadiya",
  "الصباحية": "sabahiya",
  "الفنطاس": "fintas",
  "المهبولة": "mahboula",
  "العقيلة": "eqaila",
  "الضباعية": "dhubaiya",
  "الجليعة": "julaia",
  "الزور": "zour",
  "بنيدر": "bneider",
  "النويصيب": "nuwaiseeb",
  "جنوب سعد العبدالله": "south_saad_al_abdullah",
  "النسيم الجنوبي": "south_naseem",
  "امغرة الصناعية": "amghara_industrial",
  "اسطبلات الجهراء": "jahra_stables",
  "الجهراء الصناعية": "jahra_industrial",
  "سعد العبدالله": "saad_al_abdullah",
  "الجهراء": "jahra",
  "النعيم": "naeem",
  "القصر": "qasr",
  "الواحة": "waha",
  "تيماء": "taima",
  "الصليبية": "sulaibiya",
  "العيون": "oyoun",
  "الصبية": "subiya",
  "النسيم": "naseem",
  "كبد": "kabad",
  "المطلاع": "mutlaa",
  "الخويسات": "khusais",
  "الهجن": "hejin",
  "العبدلي": "abdali",
  "السالمي": "salmi",
  "النعايم": "naaim",
  "اسواق القرين - غرب ابوفطيرة الحرفية": "west_abu_fatira_craft_zone_aswaq_al_qurain",
  "مبارك الكبير": "mubarak_al_kabeer",
  "القرين": "qurain",
  "القصور": "qusour",
  "العدان": "adan",
  "المسيلة": "messila",
  "صباح السالم": "sabah_al_salem",
  "أبو فطيرة": "abu_fatira",
  "أبو الحصانية": "abu_hasaniya",
  "الفنيطيس": "funaitees",
  "المسايل": "maseila",
  "صبحان": "sabhan",

  // -------------------------------------------------------------------------
  // Common Arabic spelling / chat variants → same Firestore areaCode.
  // extractAreaFromText sorts by name length (longest first) so longer official
  // names (e.g. "الجهراء الصناعية") still win over short prefixes like "الجهرا".
  // -------------------------------------------------------------------------
  "الجهرا": "jahra",
  "جهراء": "jahra",
  "القادسيه": "qadisiya",
  "القادسيا": "qadisiya",
  "المهبوله": "mahboula",
  "الصباحيه": "sabahiya",
  "العقيله": "eqaila",
  "قرطبه": "qurtuba",
  "العارضيه": "ardiya",
};
