// File generated by FlutterFire CLI (modified formatting by developer).
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Usage:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
          'Reconfigure using FlutterFire CLI.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// 🌐 Web Configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIcHmRZlVZyfGlhlYKPUxuNo4jb9876gc',
    appId: '1:834475197860:web:8e6cf2ebdd8147dce4ed31',
    messagingSenderId: '834475197860',
    projectId: 'aqarai-caf5d',
    authDomain: 'aqarai-caf5d.firebaseapp.com',
    storageBucket: 'aqarai-caf5d.firebasestorage.app',
    measurementId: 'G-9ZEELBZ0FY',
  );

  /// 🤖 Android Configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMxc0jF8ClL0cPIrwkwsATV5bFrhVfUzM',
    appId: '1:834475197860:android:193981b9a8fc80b6e4ed31',
    messagingSenderId: '834475197860',
    projectId: 'aqarai-caf5d',
    storageBucket: 'aqarai-caf5d.firebasestorage.app',
  );

  /// 🍏 iOS Configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfmsFP3ZpVJCq1hUJIAweZwnMNNPWpDo',
    appId: '1:834475197860:ios:b528903f2bf32962e4ed31',
    messagingSenderId: '834475197860',
    projectId: 'aqarai-caf5d',
    storageBucket: 'aqarai-caf5d.firebasestorage.app',
    iosBundleId: 'com.salmuqled.aqarai',
  );

  /// 🍎 macOS Configuration (معدّل ليطابق iOS)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXfmsFP3ZpVJCq1hUJIAweZwnMNNPWpDo',
    appId: '1:834475197860:ios:80374ac8ccb543dee4ed31',
    messagingSenderId: '834475197860',
    projectId: 'aqarai-caf5d',
    storageBucket: 'aqarai-caf5d.firebasestorage.app',
    iosBundleId: 'com.salmuqled.aqarai', // ✔ تم التوحيد
  );

  /// 🪟 Windows Configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIcHmRZlVZyfGlhlYKPUxuNo4jb9876gc',
    appId: '1:834475197860:web:8b4b7ea618d64a50e4ed31',
    messagingSenderId: '834475197860',
    projectId: 'aqarai-caf5d',
    authDomain: 'aqarai-caf5d.firebaseapp.com',
    storageBucket: 'aqarai-caf5d.firebasestorage.app',
    measurementId: 'G-DNGFHKXB01',
  );
}
